// 集团军级红蓝对抗动态编组系统 v0.3.1
// 说明：结构按公开信息做游戏化抽象，不对应任何现实部队番号、部署或实时战备数据。
import { ModernBrigadeSystem } from './ModernBrigadeSystem.js';

const TYPE_NAMES={heavy:'重型合成旅',medium:'中型合成旅',light:'轻型合成旅',mountain:'山地合成旅',amphibious:'两栖合成旅',urban_assault:'城市突击合成旅',recon_strike:'侦察突击合成旅'};
const SIDE_NAME={RED:'红方',BLUE:'蓝方'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

function unit(id,name,faction,type,echelon,q,r,manpower,attack,defense,movement,range,equipmentName,qty,parentHQ,formation){
 return {id,name:`${name}｜${equipmentName}`,fullName:name,faction,type,echelon,q,r,strength:100,maxStrength:100,
  manpower,maxManpower:manpower,attack,defense,movement,movementPoints:movement,maxMovementPoints:movement,
  actionPoints:4,maxActionPoints:4,range,morale:85,ammo:100,fuel:100,repairParts:30,supply:100,parentHQ,formation,
  movementClass:['artillery','engineer'].includes(type)?'tracked':(type==='special_forces'?'foot':(type==='amphibious'?'amphibious':'wheeled')),
  autoGenerated:true,generatedBy:'GroupArmySystem',equipment:[{type:equipmentName,name:equipmentName,initial:qty,operational:qty,damaged:0,destroyed:0}],
  equipmentSummary:`${equipmentName} ${qty}/${qty}`,modern:{c2:100,intelLevel:0,supply:100,ammo:100,fuel:100,parentHQ}};
}

// 非对称集团军部署区。坐标按 128×84 基准地图定义，并按实际地图尺寸缩放。
// 不使用镜像翻转：红蓝双方拥有不同的道路、山地、城区和纵深条件。
const DEPLOYMENT_ANCHORS={
 RED:[
  {q:18,r:19,label:'西北山地纵深集结区'},
  {q:34,r:46,label:'西部峡谷机动地域'},
  {q:27,r:79,label:'西南荒漠保障地域'},
  {q:61,r:91,label:'南部湿地外缘预备地域'},
  {q:12,r:38,label:'西部战役预备地域'}, {q:48,r:98,label:'南部战役预备地域'}
 ],
 BLUE:[
  {q:131,r:17,label:'东北机场纵深地域'},
  {q:136,r:44,label:'东部新城外缘地域'},
  {q:116,r:76,label:'东南工业纵深地域'},
  {q:145,r:88,label:'滨海军港预备地域'},
  {q:124,r:55,label:'东部战役预备地域'}, {q:118,r:101,label:'东南战役预备地域'}
 ]
};
const ARMY_REAR={RED:{q:14,r:65},BLUE:{q:146,r:36}};
const scaleAnchor=(a,W,H)=>({q:Math.round(a.q*(W/160)),r:Math.round(a.r*(H/104)),label:a.label});

const LJ27_ANCHORS={
 RED:[{q:24,r:57,label:'浙西衢州方向'},{q:45,r:66,label:'金衢西部方向'},{q:56,r:86,label:'浙西南纵深'},{q:67,r:51,label:'建德—桐庐方向'},{q:32,r:44,label:'西北战役预备地域'},{q:49,r:103,label:'西南战役预备地域'}],
 BLUE:[{q:38,r:61,label:'衢州—龙游前沿迟滞地域'},{q:68,r:62,label:'金华—义乌防御地域'},{q:91,r:30,label:'杭州—绍兴纵深地域'},{q:119,r:45,label:'宁波东部纵深地域'},{q:86,r:12,label:'北部外线增援入口'},{q:132,r:76,label:'东部沿海增援入口'}]
};
function relocateBrigade(units, side, brigadeIndex, brigadeType, W,H,isLJ27=false){
 const source=(isLJ27?LJ27_ANCHORS:DEPLOYMENT_ANCHORS);
 const raw=(source[side]??source.RED)[brigadeIndex]??source[side][0];
 const anchor=isLJ27?{...raw}:scaleAnchor(raw,W,H);
 const sourceHQ=units.find(u=>u.echelon==='brigade');
 const dq=anchor.q-(sourceHQ?.q??anchor.q), dr=anchor.r-(sourceHQ?.r??anchor.r);
 const oldPrefix=side+'_'; const newPrefix=`${side}_BDE${brigadeIndex+1}_`;
 const idMap=new Map();
 for(const u of units){const old=u.id;u.id=newPrefix+old.replace(oldPrefix,'');idMap.set(old,u.id);}
 for(const u of units){
   if(u.parentHQ&&idMap.has(u.parentHQ))u.parentHQ=idMap.get(u.parentHQ);
   u.q=clamp(u.q+dq,2,W-3);u.r=clamp(u.r+dr,2,H-3);
   u.formation=`${SIDE_NAME[side]}第${brigadeIndex+1}${TYPE_NAMES[brigadeType]??'合成旅'}${u.echelon==='brigade'?'':('·'+(u.formation??''))}`;
   u.deploymentArea=anchor.label;
   u.brigadeIndex=brigadeIndex+1;u.brigadeType=brigadeType;
   if(u.echelon==='brigade')u.fullName=`${SIDE_NAME[side]}第${brigadeIndex+1}${TYPE_NAMES[brigadeType]}`;
 }
 return units;
}

function armyDirect(side,W,H){
 const base=scaleAnchor(ARMY_REAR[side]??ARMY_REAR.RED,W,H), rearQ=base.q, mid=base.r, dir=side==='RED'?1:-1, s=SIDE_NAME[side];
 const hq=`${side}_GA_HQ`, form=`${s}集团军直属`;
 const a=[
  unit(hq,`${s}集团军指挥所`,side,'headquarters','army',rearQ,mid,260,2,15,3,1,'集团军野战指挥系统',12,null,form),
  unit(`${side}_GA_C2`,`${s}集团军直属通信指挥分队`,side,'headquarters','battalion',rearQ+dir*2,mid-3,120,2,9,4,1,'野战通信指挥车',10,hq,form),
  unit(`${side}_GA_RECON`,`${s}集团军直属侦察情报分队`,side,'recon','battalion',rearQ+dir*5,mid-7,150,5,7,7,5,'战役侦察无人机系统',12,hq,form),
  unit(`${side}_GA_ART1`,`${s}集团军炮兵旅远程火力营`,side,'artillery','battalion',rearQ+dir*5,mid-10,180,16,6,4,8,'远程火箭炮系统',12,hq,form),
  unit(`${side}_GA_ART2`,`${s}集团军炮兵旅自行火炮营`,side,'artillery','battalion',rearQ+dir*5,mid+10,180,14,7,4,7,'自行榴弹炮系统',18,hq,form),
  unit(`${side}_GA_AD`,`${s}集团军防空旅防空营`,side,'air_defense','battalion',rearQ+dir*3,mid-7,180,9,9,5,6,'野战防空系统',12,hq,form),
  unit(`${side}_GA_AVN`,`${s}集团军陆航旅支援群`,side,'support','battalion',rearQ+dir*2,mid+7,190,11,7,8,6,'武装/运输直升机群',16,hq,form),
  unit(`${side}_GA_SOF`,`${s}集团军特战旅任务分队`,side,'special_forces','company',rearQ+dir*7,mid,70,10,8,8,3,'特战多域任务套件',8,hq,form),
  unit(`${side}_GA_ENG`,`${s}集团军直属工程保障营`,side,'engineer','battalion',rearQ+dir*3,mid+4,190,4,9,4,1,'重型工程保障车辆',16,hq,form),
  unit(`${side}_GA_CROSS`,`${s}集团军两栖浮渡分队`,side,'amphibious','company',rearQ+dir*5,mid+5,120,6,7,6,1,'两栖装甲输送/浮渡车辆',12,hq,form),
  unit(`${side}_GA_LOG`,`${s}集团军勤务保障力量`,side,'supply','battalion',rearQ+dir,mid+4,260,2,9,4,1,'综合补给运输车辆',30,hq,form),
  unit(`${side}_GA_REC`,`${s}集团军装备抢修营`,side,'support','battalion',rearQ+dir,mid-4,180,2,10,4,1,'重型装甲抢修车',12,hq,form),
  unit(`${side}_GA_MED`,`${s}集团军卫勤保障分队`,side,'support','battalion',rearQ+dir,mid+8,150,1,8,4,1,'野战医疗保障车辆',12,hq,form)
 ];
 const av=a.find(x=>x.id.endsWith('_AVN'));av.airSupportProvider=true;av.helicopterDeck=['直-10武装直升机','直-19武装侦察直升机','直-20战术通用直升机'];
 const sof=a.find(x=>x.id.endsWith('_SOF'));sof.airDroppable=true;sof.reconRadius=7;sof.stealth=3;sof.multiDomain=true;
 const crossing=a.find(x=>x.id.endsWith('_CROSS'));
 if(crossing){crossing.movementClass='amphibious';crossing.amphibious=true;crossing.canFloatCross=true;crossing.waterMobility='amphibious_support';crossing.waterMovementCost=2;crossing.role='浮渡、夺控水上/水库要点、建立渡场';}
 const log=a.find(x=>x.id.endsWith('_LOG'));log.logisticsProvider=true;log.logisticsRadius=8;
 const rec=a.find(x=>x.id.endsWith('_REC'));rec.logisticsProvider=true;rec.repairLevel=4;rec.logisticsRadius=6;rec.recoveryVehicle=true;
 const med=a.find(x=>x.id.endsWith('_MED'));med.medicalCapacity=30;med.logisticsRadius=6;
 return a;
}

function attachHierarchy(units,side){
 const armyHQ=`${side}_GA_HQ`;
 for(const u of units){
  if(u.echelon==='brigade'){u.parentHQ=armyHQ;u.commandLevel='旅';}
  else if(u.echelon==='battalion'){u.commandLevel='营';}
  else if(u.echelon==='company'){u.commandLevel='连';}
  else if(u.echelon==='team'){u.commandLevel='小队';}
 }
}

function deconflict(units,W,H){
 const used=new Set();
 for(const u of units){let q=clamp(Math.round(u.q),1,W-2),r=clamp(Math.round(u.r),1,H-2);let k=`${q},${r}`;
  if(used.has(k)){outer:for(let rad=1;rad<12;rad++)for(let dr=-rad;dr<=rad;dr++)for(let dq=-rad;dq<=rad;dq++){const nq=q+dq,nr=r+dr,nk=`${nq},${nr}`;if(nq>0&&nr>0&&nq<W-1&&nr<H-1&&!used.has(nk)){q=nq;r=nr;k=nk;break outer;}}}
  u.q=q;u.r=r;used.add(k);
 }
 return units;
}

export class GroupArmySystem{
 static isGroupArmy(config){return config?.groupArmySelection===true;}
 static getSelection(){try{return JSON.parse(sessionStorage.getItem('groupArmySelection')||'{}');}catch{return {};}}
 static getSupportSelection(){try{return JSON.parse(sessionStorage.getItem('groupArmySupportSelection')||'{}');}catch{return {};}}
 static generate(config){
  const W=Number(config?.trainingMap?.width??config?.map?.width??160),H=Number(config?.trainingMap?.height??config?.map?.height??104),sel=this.getSelection(),supportSel=this.getSupportSelection();
  const defaults={red:['heavy','heavy','medium','light','medium','mountain'],blue:['heavy','medium','medium','mountain','heavy','light']};
  const out=[];
  for(const side of ['RED','BLUE']){
   const key=side.toLowerCase(), types=(sel[key]?.length?sel[key]:defaults[key]).slice(0,6);
   out.push(...armyDirect(side,W,H));
   types.forEach((type,i)=>{
    // 复用已经验证过的合成旅生成器，再重定位并挂入集团军指挥链。
    sessionStorage.setItem('modernBrigadeSelection',JSON.stringify({red:type,blue:type}));
    const pair=ModernBrigadeSystem.generate({...config,groupArmySelection:false,modernBrigadeSelection:true});
    const own=pair.filter(u=>u.faction===side);
    out.push(...relocateBrigade(own,side,i,type,W,H,(config?.id==='lijian27_zhejiang'||config?.key==='lijian27_zhejiang')));
    if(i>=4){const turn=side==='RED'?(i===4?10:16):(i===4?8:14);for(const u of own){u.reinforcementGroup=`LJ27_${side}_RESERVE_${i+1}`;u.reinforcementTurn=turn;u.reinforcementName=`${SIDE_NAME[side]}集团军第${i+1}合成旅战役预备队`;u.reinforcementDetail=(side==='BLUE'&&i===4)?`第${turn}回合由北部外线投入战役`:(side==='BLUE'&&i===5)?`第${turn}回合由东部沿海投入战役`:`第${turn}回合投入战役`;u.entryPoint={q:u.q,r:u.r};u.entryRadius=8;u.offMap=true;}}
   });

   if(config?.id==='lijian27_zhejiang'||config?.key==='lijian27_zhejiang'){
    if(side==='BLUE'){
      const garr=[[88,27,'杭州地方守备群'],[102,36,'绍兴地方守备群'],[123,44,'宁波地方守备群'],[70,63,'金华地方守备群'],[123,75,'台州地方守备群'],[80,94,'丽水地方守备群'],[123,102,'温州地方守备群']];
      garr.forEach((x,i)=>{const u=unit(`BLUE_GARR_${i+1}`,x[2],side,'infantry','battalion',x[0],x[1],420,8,15,3,1,'地方守备轻步兵装备',1,`${side}_GA_HQ`,'蓝方地方守备力量');u.localDefense=true;u.canBuildSimpleFortification=true;out.push(u);});
      // v1.3.9：县域守备网。每个县级节点1个蓝方武警演习守备中队（连级）。
      // 仅为架空红蓝演习编制，不对应现实武警单位番号、驻地或战备部署。
      const countyPAP=[[81,58,"义乌"],[70,28,"临安"],[40,46,"淳安"],[56,48,"建德"],[88,48,"诸暨"],[102,54,"嵊州"],[48,105,"龙泉"],[76,75,"永康"],[118,93,"乐清"],[82,14,"德清"],[64,10,"安吉"],[72,4,"长兴"],[93,14,"桐乡"],[100,18,"海宁"],[108,15,"海盐"],[110,9,"平湖"],[78,34,"富阳"],[68,40,"桐庐"],[93,32,"萧山"],[104,60,"新昌"],[112,36,"余姚"],[116,28,"慈溪"],[120,51,"奉化"],[123,60,"宁海"],[134,54,"象山"],[27,70,"江山"],[30,62,"常山"],[24,51,"开化"],[50,62,"龙游"],[64,58,"兰溪"],[76,51,"浦江"],[86,64,"东阳"],[93,70,"磐安"],[74,74,"武义"],[108,68,"天台"],[102,78,"仙居"],[117,72,"临海"],[129,81,"温岭"],[134,92,"玉环"],[84,86,"缙云"],[102,96,"青田"],[63,92,"遂昌"],[69,96,"松阳"],[72,104,"云和"],[57,116,"庆元"],[75,110,"景宁"],[122,108,"瑞安"],[120,114,"平阳"],[122,118,"苍南"],[111,98,"永嘉"],[126,66,"三门"],[106,110,"文成"],[104,118,"泰顺"],[141,31,"岱山"],[143,21,"嵊泗"]];
      countyPAP.forEach((x,i)=>{
        const u=unit(`BLUE_PAP_${i+1}`,`${x[2]}武警演习守备中队`,side,'infantry','company',x[0],x[1],120,6,11,4,1,'武警机动/守备装备',1,`${side}_GA_HQ`,'蓝方县域武警守备力量');
        u.localDefense=true;u.countySecurity=true;u.armedPoliceExerciseUnit=true;u.canBuildSimpleFortification=true;u.canCaptureObjective=true;u.controlWeight=1;
        u.role='县城守备、交通节点警戒、后方安全与迟滞';u.fictionalExerciseUnit=true;
        out.push(u);
      });
    }
    // 金华方向的既设火箭军演习阵地属于蓝方地方常备兵力，不受集团军支援卡组选择影响。
    if(side==='BLUE'){
      const localRf=unit('BLUE_LOCAL_ROCKET_JH','蓝方金华方向火箭军常备任务分队',side,'artillery','battalion',63,69,220,20,9,4,12,'演习远程导弹发射系统',6,`${side}_GA_HQ`,'蓝方地方常备远程火力');
      localRf.rocketForce=true;localRf.localStandingForce=true;localRf.fictionalExerciseUnit=true;localRf.canCaptureObjective=false;localRf.supportCard=null;localRf.role='金华方向地方常备远程火力与阵地守备';out.push(localRf);
    }
    // 玩家额外选择的“演习配属火箭军”属于集团军配属部队：红方部署在西部后方，绝不占用金华蓝方既设发射地域。
    if(supportSel?.rocketForce?.[side.toLowerCase()] === true){
      const rq=side==='RED'?20:116, rr=side==='RED'?84:20;
      const rf=unit(`${side}_ROCKET_TASK`,`${SIDE_NAME[side]}火箭军演习配属任务分队`,side,'artillery','battalion',rq,rr,180,20,7,4,12,'演习远程导弹发射系统',6,`${side}_GA_HQ`,`${SIDE_NAME[side]}集团军配属远程火力`);
      rf.rocketForce=true;rf.fictionalExerciseUnit=true;rf.canCaptureObjective=false;rf.supportCard=null;rf.attachedExerciseForce=true;out.push(rf);
    }
   }
   attachHierarchy(out.filter(u=>u.faction===side),side);
  }
  return deconflict(out,W,H);
 }
 static templateInfo(){return TYPE_NAMES;}
}
