// 现代合成旅动态编组系统 v0.1.3
// 旅级骨架按公开资料抽象；具体装备数量/战斗参数均为游戏化数值。
const EQUIPMENT = {
 ZTZ99A:{name:"ZTZ-99A主战坦克"}, ZBD04A:{name:"ZBD-04A步兵战车"}, PLZ05:{name:"PLZ-05自行榴弹炮"},
 HQ17A:{name:"红旗-17A野战防空系统"}, ZTL11:{name:"ZTL-11轮式突击车"}, ZBL08:{name:"ZBL-08轮式步兵战车"},
 PCL181:{name:"PCL-181车载榴弹炮"}, CSK181:{name:"CSK-181装甲高机动车"},
 PCP001:{name:"轻型火力支援车"}, ZBD03:{name:"ZBD-03空降战车"}, ZBD05:{name:"ZBD-05两栖步兵战车"}, ZTD05:{name:"ZTD-05两栖突击车"}, UAV_RECON:{name:"战术侦察无人机系统"},
 ENG_VEH:{name:"装甲工程保障车辆"}, LOG_VEH:{name:"综合保障车辆"},
 HREC:{name:"重型装甲抢修车"}, WREC:{name:"轮式装甲抢修车"}, LREC:{name:"轻型机动抢修车"}, AREC:{name:"两栖装甲抢修车"},
 SOF_KIT:{name:"特战多域侦察作战套件"},
 DF11A:{name:"DF-11A常规导弹系统"}, DF15B:{name:"DF-15B常规导弹系统"}, DF16:{name:"DF-16常规导弹系统"},
 DF17:{name:"DF-17常规导弹系统"}, CJ10:{name:"CJ-10巡航导弹系统"}, DF21C:{name:"DF-21C常规导弹系统"}, DF26:{name:"DF-26常规导弹系统"},
 RF_C2:{name:"火箭军机动指挥系统"}, RF_SUP:{name:"火箭军综合保障车辆"}, RF_TECH:{name:"火箭军技术保障车辆"}
};
const TEMPLATES = {
 heavy:{name:"重型合成旅",maneuver:"heavy",tank:"ZTZ99A",ifv:"ZBD04A",art:"PLZ05",ad:"HQ17A",support:"ZBD04A",atk:1.12,def:1.15,mov:.92,profile:"正面突破",engineers:2,sof:2},
 medium:{name:"中型合成旅",maneuver:"medium",tank:"ZTL11",ifv:"ZBL08",art:"PCL181",ad:"HQ17A",support:"ZBL08",atk:1.02,def:.98,mov:1.16,profile:"通用机动",engineers:2,sof:2},
 light:{name:"轻型合成旅",maneuver:"light",tank:"CSK181",ifv:"CSK181",art:"PCL181",ad:"HQ17A",support:"PCP001",atk:.90,def:.86,mov:1.25,profile:"快速机动",engineers:2,sof:2},
 mountain:{name:"山地合成旅",maneuver:"mountain",tank:"CSK181",ifv:"CSK181",art:"PCL181",ad:"HQ17A",support:"PCP001",atk:.94,def:1.04,mov:1.18,profile:"山地/复杂地形",engineers:2,sof:2},
 amphibious:{name:"两栖合成旅",maneuver:"amphibious",tank:"ZTD05",ifv:"ZBD05",art:"PLZ05",ad:"HQ17A",support:"ZBD05",atk:1.04,def:.96,mov:1.08,profile:"渡河/水网",engineers:2,sof:2},
 urban_assault:{name:"城市突击合成旅",maneuver:"urban_assault",tank:"ZTZ99A",ifv:"ZBD04A",art:"PLZ05",ad:"HQ17A",support:"ENG_VEH",atk:1.08,def:1.08,mov:.92,profile:"城市攻坚",engineers:3,sof:1},
 recon_strike:{name:"侦察突击合成旅",maneuver:"recon_strike",tank:"ZTL11",ifv:"ZBL08",art:"PCL181",ad:"HQ17A",support:"CSK181",atk:.98,def:.88,mov:1.28,profile:"侦察/快速机动",engineers:2,sof:3}
};
const eqName=id=>EQUIPMENT[id]?.name??id;
function make(id,name,faction,type,echelon,q,r,personnel,attack,defense,movement,range,equipment,qty,formation,parentHQ=null){
 // v1.0.0: 所有现代合成旅（红/蓝军及由其转换的解放军）统一攻击力×2。
 // 倍率放在动态编组生成层，避免各场景重复叠乘。
 attack = Math.max(0, Number(attack ?? 0) * 2);
 let movementClass = ({tank:"tracked",mechanized_infantry:"tracked",wheeled_infantry:"wheeled",amphibious_armor:"amphibious",motorized_infantry:"wheeled",headquarters:"wheeled",support:"wheeled",supply:"wheeled",engineer:"tracked",air_defense:"wheeled",artillery:"tracked",recon:"wheeled",special_forces:"foot"}[type] || "foot");
 // 水上机动分级：普通浮渡 / 专业两栖。ZBD-04A具备有限自行浮渡能力；05系列为专业两栖。
 let waterMobility = "none";
 let waterMovementCost = Infinity;
 if (equipment === "ZBD04A") {
  movementClass = "tracked";
  waterMobility = "float_crossing";
  waterMovementCost = 4;
 }
 if (["ZTD05","ZBD05"].includes(equipment)) {
  movementClass = "amphibious";
  waterMobility = "amphibious_assault";
  waterMovementCost = 2;
 }
 if (equipment === "AREC") {
  movementClass = "amphibious";
  waterMobility = "amphibious_support";
  waterMovementCost = 3;
 }
 if (equipment === "PCL181") movementClass = "wheeled";
 if (type === "special_forces") {
  movementClass = "foot";
  waterMobility = "ford";
  waterMovementCost = 3;
 }
 const infantryEngineering = ["infantry","mechanized_infantry","wheeled_infantry","motorized_infantry","special_forces"].includes(type)
  ? {canEntrench:true,canBuildAA1:true,fortificationPower:25}
  : null;
 const unit = {id,name:`${name}｜${eqName(equipment)}`,fullName:name,faction,side:(faction==="RED"?"red":faction==="BLUE"?"blue":String(faction??"").toLowerCase()),type,echelon,q,r,strength:100,maxStrength:100,
  manpower:personnel,maxManpower:personnel,attack,defense,movement,movementPoints:movement,maxMovementPoints:movement,
  actionPoints:4,maxActionPoints:4,range,morale:82,ammo:100,fuel:100,repairParts:20,supply:100,formation,parentHQ,movementClass,
  autoGenerated:true, generatedBy:"ModernBrigadeSystem", logisticsProvider:["support","supply"].includes(type), logisticsRadius:type==="supply"?5:(type==="support"?3:0),
  equipment:[{type:equipment,name:eqName(equipment),initial:qty,operational:qty,damaged:0,destroyed:0}],
  equipmentSummary:`${eqName(equipment)} ${qty}/${qty}辆`,amphibious:movementClass==="amphibious",waterMobility,waterMovementCost,canFloatCross:waterMobility!=="none",
  engineering:infantryEngineering,
  engineerKits:type==="engineer"?10:undefined,maxEngineerKits:type==="engineer"?10:undefined,
  modern:{c2:100,intelLevel:0,supply:100,ammo:100,fuel:100,parentHQ}};
 // 现代编组内所有特战小队统一具备空降资格，避免营属特战能空降而旅直属特战不能空降。
 if(type === "special_forces") { unit.airDroppable=true; unit.airDropUsed=false; unit.airborneCapable=true; }
 return unit;
}
function maneuverCompanies(T, side, b, faction, baseQ, baseR, stepQ, stepR, form, bnHQ){
 const p=`${side}_BN${b}`; const pos=i=>({q:baseQ+stepQ*(i%2),r:baseR+stepR*Math.floor(i/2)}); const a=[];
 const add=(suffix,name,type,eq,qty,atk,def,mov,i)=>{const x=pos(i);a.push(make(`${p}_${suffix}`,name,faction,type,"company",x.q,x.r,(type==="tank"||type==="amphibious_armor"?95:(type.includes("infantry")?125:110)),Math.round(atk*T.atk),Math.round(def*T.def),Math.max(4,Math.round(mov*T.mov)),type==="tank"?2:1,eq,qty,form,bnHQ));};
 if(T.maneuver==="heavy"){
  add("T1",`第${b}合成营坦克1连`,"tank",T.tank,14,12,10,5,0); add("T2",`第${b}合成营坦克2连`,"tank",T.tank,14,12,10,5,1);
  add("M1",`第${b}合成营装甲步兵1连`,"mechanized_infantry",T.ifv,14,9,9,5,2); add("M2",`第${b}合成营装甲步兵2连`,"mechanized_infantry",T.ifv,14,9,9,5,3);
 } else if(T.maneuver==="medium"){
  add("A1",`第${b}合成营轮式突击连`,"tank",T.tank,14,10,8,6,0);
  add("M1",`第${b}合成营轮式装步1连`,"wheeled_infantry",T.ifv,14,9,8,6,1); add("M2",`第${b}合成营轮式装步2连`,"wheeled_infantry",T.ifv,14,9,8,6,2); add("M3",`第${b}合成营轮式装步3连`,"wheeled_infantry",T.ifv,14,9,8,6,3);
 } else if(T.maneuver==="amphibious"){
  add("A1",`第${b}合成营两栖突击1连`,"amphibious_armor",T.tank,14,11,8,6,0);
  add("A2",`第${b}合成营两栖突击2连`,"amphibious_armor",T.tank,14,11,8,6,1);
  add("M1",`第${b}合成营两栖装步1连`,"mechanized_infantry",T.ifv,14,9,8,6,2); add("M2",`第${b}合成营两栖装步2连`,"mechanized_infantry",T.ifv,14,9,8,6,3);
 } else if(T.maneuver==="urban_assault"){
  add("T1",`第${b}合成营城市突击坦克连`,"tank",T.tank,12,11,10,5,0);
  add("M1",`第${b}合成营装甲突击步兵1连`,"mechanized_infantry",T.ifv,14,10,10,5,1);
  add("M2",`第${b}合成营装甲突击步兵2连`,"mechanized_infantry",T.ifv,14,10,10,5,2);
  add("AS",`第${b}合成营突击步兵连`,"infantry","SOF_KIT",10,10,9,6,3);
 } else if(T.maneuver==="recon_strike"){
  add("A1",`第${b}合成营轮式突击连`,"tank",T.tank,12,10,7,7,0);
  add("M1",`第${b}合成营快速装步1连`,"wheeled_infantry",T.ifv,12,9,7,8,1);
  add("M2",`第${b}合成营快速装步2连`,"wheeled_infantry",T.ifv,12,9,7,8,2);
  add("R1",`第${b}合成营侦察突击连`,"recon","UAV_RECON",8,8,6,8,3);
 } else if(T.maneuver==="mountain"){
  for(let i=0;i<3;i++) add(`M${i+1}`,`第${b}合成营山地步兵${i+1}连`,"infantry",T.ifv,18,8,8,7,i);
  add("FS",`第${b}合成营山地火力支援连`,"motorized_infantry",T.support,12,10,7,6,3);
 } else {
  for(let i=0;i<4;i++) add(`L${i+1}`,`第${b}合成营高机动步兵${i+1}连`,"motorized_infantry",T.ifv,18,8,7,7,i);
 }
 const s=pos(4);
 const recoveryEq={heavy:"HREC",medium:"WREC",light:"LREC",mountain:"LREC",amphibious:"AREC",urban_assault:"HREC",recon_strike:"WREC"}[T.maneuver]||"WREC";
 const sup=make(`${p}_SUP`,`第${b}合成营维修保障连`,faction,"support","company",s.q,s.r,96,3,7,5,1,recoveryEq,6,form,bnHQ);
 sup.logisticsRole="battalion_repair"; sup.repairLevel=2; sup.medicalCapacity=6; sup.logisticsRadius=3; a.push(sup);
 const so=pos(5);
 const sof=make(`${p}_SOF`,`第${b}合成营直属特战小队`,faction,"special_forces","team",so.q,so.r,18,8,6,7,2,"SOF_KIT",6,form,bnHQ);
 sof.airDroppable=true; sof.reconRadius=5; sof.stealth=2; sof.multiDomain=true; sof.maxActionPoints=5; sof.actionPoints=5; a.push(sof);
 return a;
}
function brigade(side,type,flip=false,config={}){
 const T=TEMPLATES[type]??TEMPLATES.heavy, faction=side, prefix=side;
 // 红方部署在西侧，蓝方部署在东侧；旅指挥/火力/保障置于纵深，四个合成营分上下两梯队。
 const W=Number(config?.trainingMap?.width??60), H=Number(config?.trainingMap?.height??40);
 const rearQ=flip?W-6:5, frontQ=flip?W-14:13, dir=flip?-1:1, arr=[];
 const bdeHQ=`${prefix}_BDE_HQ`;
 arr.push(make(bdeHQ,`${side==="RED"?"红方":"蓝方"}${T.name}旅指挥所`,faction,"headquarters","brigade",rearQ,Math.round(H*.50),85,3,12,3,1,"LOG_VEH",8,T.name,null));
 const anchors=[{q:frontQ,r:Math.round(H*.23)},{q:frontQ,r:Math.round(H*.40)},{q:frontQ-dir*4,r:Math.round(H*.62)},{q:frontQ-dir*4,r:Math.round(H*.79)}];
 anchors.forEach((p,i)=>{
  const b=i+1,bnHQ=`${prefix}_BN${b}_HQ`,form=`${T.name}·第${b}合成营`;
  arr.push(make(bnHQ,`第${b}合成营指挥所`,faction,"headquarters","battalion",p.q-dir*2,p.r,55,3,9,4,1,"LOG_VEH",4,form,bdeHQ));
  arr.push(...maneuverCompanies(T,prefix,b,faction,p.q,p.r-1,dir*2,2,form,bnHQ));
  // 每个合成营配置1个随行野战防空分队，随营机动并受营指挥所指挥。
  const bad=make(`${prefix}_BN${b}_AD`,`第${b}合成营随行防空分队`,faction,"air_defense","platoon",p.q-dir*3,p.r-3,48,5,6,5,3,T.ad,3,form,bnHQ);
  bad.airDefenseRadius=3; bad.battalionEscort=true; arr.push(bad);
 });
 arr.push(make(`${prefix}_ART1`,"旅炮兵营第1火力连",faction,"artillery","company",rearQ+dir*4,Math.max(3,Math.round(H*.32)),85,13,5,4,6,T.art,6,T.name,bdeHQ));
 arr.push(make(`${prefix}_ART2`,"旅炮兵营第2火力连",faction,"artillery","company",rearQ+dir*4,Math.min(H-3,Math.round(H*.68)),85,13,5,4,6,T.art,6,T.name,bdeHQ));
 arr.push(make(`${prefix}_AD`,"旅防空营野战防空连",faction,"air_defense","company",rearQ+dir*2,Math.round(H*.42),90,7,7,4,4,T.ad,6,T.name,bdeHQ));
 arr.push(make(`${prefix}_RECON`,"旅侦察营无人侦察连",faction,"recon","company",frontQ+dir*3,Math.round(H*.50),75,4,5,7,4,"UAV_RECON",6,T.name,bdeHQ));
 arr.push(make(`${prefix}_C2`,"旅直属通信指挥连",faction,"headquarters","company",rearQ+dir,Math.round(H*.46),90,2,7,5,1,"LOG_VEH",8,T.name,bdeHQ));
 arr.push(make(`${prefix}_EW`,"旅直属电子对抗分队",faction,"recon","company",rearQ+dir*2,Math.round(H*.50),70,3,5,5,4,"UAV_RECON",6,T.name,bdeHQ));
 arr.push(make(`${prefix}_MED`,"旅勤务保障营卫勤连",faction,"support","company",rearQ,Math.round(H*.66),95,1,6,4,1,"LOG_VEH",8,T.name,bdeHQ));
 // 工程力量重构：所有现代合成旅固定配置4个营属工兵单位。
 // 这样四个合成营各有1个工程连，不再依赖少量旅直属工兵来保障全部重装备。
 // 相比此前多数旅型的2个工程单位，统一增加2个；城市突击旅也统一为4个。
 const battalionEngineerCount=4;
 for(let i=1;i<=battalionEngineerCount;i++){
  const bnHQ=`${prefix}_BN${i}_HQ`;
  const anchor=anchors[i-1] || anchors[0];
  const eng=make(
   `${prefix}_BN${i}_ENG`,
   `第${i}合成营工兵连`,
   faction,"engineer","company",
   anchor.q-dir*3,anchor.r+3,
   115,5,7,4,1,"ENG_VEH",10,`${T.name}·第${i}合成营`,bnHQ
  );
  eng.engineerRole="battalion_engineer";
  eng.engineerSupportRadius=3;
  eng.canBuildFortifications=true;
  eng.canBridge=true;
  eng.canDemolish=true;
  // 显式写入工程能力，避免动态生成的营属工兵只靠 type/name 被识别。
  // 工程系统不设置任何“总建造次数”，每回合只受剩余行动点限制。
  eng.engineering={
   canEntrench:true, canBuildAdvanced:true,
   canLayMines:true, canClearMines:true,
   canBuildBridge:true, canDemolishBridge:true,
   canBuildWall:true, canDemolishWall:true,
   fortificationPower:50, mineLaying:50, mineClearing:50
  };
  arr.push(eng);
 }
 // 旅直属工兵分队：作为旅级机动工程预备力量，不替代四个营属工兵连。
 const bdeEng=make(`${prefix}_BDE_ENG`,`旅直属工兵分队`,faction,"engineer","platoon",rearQ+dir*2,Math.round(H*.56),58,4,7,5,1,"ENG_VEH",5,T.name,bdeHQ);
 bdeEng.engineerRole="brigade_engineer_detachment"; bdeEng.engineerSupportRadius=5;
 bdeEng.engineering={canEntrench:true,canBuildAdvanced:true,canLayMines:true,canClearMines:true,canBuildBridge:true,canDemolishBridge:true,canBuildWall:true,canDemolishWall:true,canBuildAA1:true,canBuildAA2:true,canBuildAA3:true,fortificationPower:50,mineLaying:50,mineClearing:50};
 arr.push(bdeEng);
 const recoveryEq={heavy:"HREC",medium:"WREC",light:"LREC",mountain:"LREC",amphibious:"AREC",urban_assault:"HREC",recon_strike:"WREC"}[T.maneuver]||"WREC";
 const log=make(`${prefix}_LOG`,"旅勤务保障营综合保障连",faction,"supply","company",rearQ,Math.round(H*.60),135,2,7,4,1,recoveryEq,12,T.name,bdeHQ);
 log.logisticsRole="brigade_recovery"; log.repairLevel=3; log.medicalCapacity=12; log.logisticsRadius=5; log.recoveryVehicle=true; arr.push(log);
 const med=arr.find(u=>u.id===`${prefix}_MED`); if(med){med.medicalCapacity=16;med.logisticsRadius=4;}
 const ew=arr.find(u=>u.id===`${prefix}_EW`); if(ew){ew.electronicWarfare=true;ew.reconRadius=4;}
 // 旅直属特战小队：轻装、侦察强，可在允许浮渡的河段自行浮渡。
 for(let i=1;i<=Math.max(1,Number(T.sof||2));i++){
  const sf=make(`${prefix}_BDE_SOF${i}`,`旅直属特战小队${i}`,faction,"special_forces","team",frontQ+dir*(4+i),Math.round(H*(i===1?.44:.56)),24,9,6,7,2,"SOF_KIT",6,T.name,bdeHQ);
  sf.reconRadius=6; sf.stealth=3; sf.maxActionPoints=5; sf.actionPoints=5; sf.canFord=true; sf.canFloatCross=true; sf.waterMobility="ford"; sf.waterMovementCost=3; arr.push(sf);
 }
 return arr;
}

// 对动态编组做最后一道坐标去重。小型训练场纵深较短，营属单位与旅炮兵容易撞格；
// 这里先在生成阶段消除同格，主系统随后再根据真实地形做合法格修复。
function deconflictGeneratedUnits(units, config={}) {
 const W=Number(config?.trainingMap?.width??60), H=Number(config?.trainingMap?.height??40);
 const used=new Set();
 const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
 for (const u of units) {
   let q=clamp(Math.round(Number(u.q)||0),0,W-1), r=clamp(Math.round(Number(u.r)||0),0,H-1);
   if (!used.has(`${q},${r}`)) { u.q=q; u.r=r; used.add(`${q},${r}`); continue; }
   let found=null;
   for(let radius=1; radius<=10 && !found; radius++) {
     for(let dr=-radius; dr<=radius && !found; dr++) {
       for(let dq=-radius; dq<=radius; dq++) {
         if(Math.max(Math.abs(dq),Math.abs(dr),Math.abs(-dq-dr))!==radius) continue;
         const nq=q+dq,nr=r+dr;
         if(nq<0||nr<0||nq>=W||nr>=H||used.has(`${nq},${nr}`)) continue;
         found={q:nq,r:nr}; break;
       }
     }
   }
   if(found){u.q=found.q;u.r=found.r;used.add(`${u.q},${u.r}`);} else {u.q=q;u.r=r;}
 }
 return units;
}


function rocketForceBrigade(side="RED",flip=false,config={}) {
 const W=Number(config?.trainingMap?.width??76), H=Number(config?.trainingMap?.height??52);
 const faction=side, prefix=side, units=[];
 const rearQ=flip?W-10:10, dir=flip?-1:1, centerR=Math.round(H*.50);
 const add=(suffix,name,type,echelon,q,r,p,a,d,m,range,eq,qty,formation,parent=null)=>{const u=make(`${prefix}_${suffix}`,name,faction,type,echelon,q,r,p,a,d,m,range,eq,qty,formation,parent); units.push(u); return u;};
 const label=side==="RED"?"红方":"蓝方", form="火箭军综合测试旅";
 const hq=add("RF_HQ",`${label}火箭军综合测试旅指挥所`,"headquarters","brigade",rearQ,centerR,120,2,8,4,1,"RF_C2",4,form);
 const models=[["DF11A","DF-11A常规导弹营",-16],["DF15B","DF-15B常规导弹营",-11],["DF16","DF-16常规导弹营",-6],["DF17","DF-17常规导弹营",-1],["CJ10","CJ-10巡航导弹营",4],["DF21C","DF-21C常规导弹营",9],["DF26","DF-26常规导弹营",14]];
 models.forEach(([eq,n,dr],i)=>{const u=add(`RF_M${i+1}`,`${label}${n}`,"artillery","battalion",rearQ+dir*3,centerR+dr,90,10+i,6,3,8+i,eq,6,form,hq.id);u.ammo=100;u.missileStock=12;u.maxMissileStock=12;u.equipmentSummary=`${eqName(eq)} 6/6辆｜导弹 12/12枚`;});
 add("RF_AD1",`${label}测试旅野战防空营`,"air_defense","battalion",rearQ+dir*7,centerR-8,110,7,9,4,4,"HQ17A",12,form,hq.id);
 add("RF_AD2",`${label}测试旅要地防空营`,"air_defense","battalion",rearQ+dir*7,centerR+8,110,7,9,4,4,"HQ17A",12,form,hq.id);
 add("RF_SUP1",`${label}综合保障营`,"supply","battalion",rearQ-dir*2,centerR-6,130,2,6,5,1,"RF_SUP",18,form,hq.id);
 add("RF_TECH",`${label}技术保障营`,"support","battalion",rearQ-dir*2,centerR+6,120,2,6,5,1,"RF_TECH",16,form,hq.id);
 const eng=add("RF_ENG",`${label}工程防化营`,"engineer","battalion",rearQ+dir*9,centerR,120,4,7,4,1,"ENG_VEH",14,form,hq.id);
 eng.engineering={canEntrench:true,canBuildAdvanced:true,canLayMines:true,canClearMines:true,canBuildBridge:true,canDemolishBridge:true,canBuildWall:true,canDemolishWall:true,fortificationPower:50,mineLaying:50,mineClearing:50};eng.engineerKits=20;eng.maxEngineerKits=20;
 return units;
}
function rocketForceTestBrigade(config={}) {
 return deconflictGeneratedUnits([...rocketForceBrigade("RED",false,config),...brigade("BLUE","heavy",true,config)],config);
}

function getRocketSupportSelection(){
 try{return JSON.parse(sessionStorage.getItem("modernRocketSupportSelection")||"{}");}catch{return {};}
}
function placeRocketSupportInReserve(units, side, config={}){
 const W=Number(config?.trainingMap?.width??76), H=Number(config?.trainingMap?.height??52);
 const left=side==="RED";
 const baseQ=left?3:Math.max(3,W-9), baseR=left?Math.max(3,H-15):3;
 const cols=7;
 units.forEach((u,i)=>{u.q=baseQ+(i%cols);u.r=baseR+Math.floor(i/cols)*3;u.rocketSupportBrigade=true;u.reserveZone=left?"RED_ROCKET_RESERVE":"BLUE_ROCKET_RESERVE";});
 return units;
}
export class ModernBrigadeSystem {
 static isModern(config){return config?.modernBrigadeSelection===true;}
 static getSelection(){try{return JSON.parse(sessionStorage.getItem("modernBrigadeSelection")||"{}");}catch{return {};}}
 static getRocketSupportSelection(){return getRocketSupportSelection();}
 static generate(config){
  const s=this.getSelection();
  if(config?.rocketForceTest===true && !s.red && !s.blue)return rocketForceTestBrigade(config);
  const makeSide=(side,type,flip)=>type==="rocket_force"?rocketForceBrigade(side,flip,config):brigade(side,type||((side==="RED")?"heavy":"medium"),flip,config);
  const all=[...makeSide("RED",s.red,false),...makeSide("BLUE",s.blue,true)];
  const rs=getRocketSupportSelection();
  // 火箭军作为可选战役支援旅，与所选主战合成旅并存，而不是替换主战旅。
  if(rs.red && s.red!=="rocket_force") all.push(...placeRocketSupportInReserve(rocketForceBrigade("RED",false,config),"RED",config));
  if(rs.blue && s.blue!=="rocket_force") all.push(...placeRocketSupportInReserve(rocketForceBrigade("BLUE",true,config),"BLUE",config));
  return deconflictGeneratedUnits(all,config);
 }
 static templateInfo(){return TEMPLATES;}
}
